### ISSUE TITLE
请问支持flink-sql嘛，DDL创建Clickhouse的sink

### ISSUE THREAD

**Issue by xiongmozhou** [ivi-ru/flink-clickhouse-sink#16]

**Comment by ashulenko** [comment]
@xiongmozhou hello, please, write in english.

**Comment by xiongmozhou** [comment]
Do you support Flink SQL? DDL creates the sink of Clickhouse

**Comment by xiongmozhou** [comment]
@ashulenko

**Comment by ashulenko** [comment]
@xiongmozhou No, flink-clickhouse-sink doesn't support Flink SQL at the moment.

**Comment by mchernyakov** [comment]
closing this issue
