### ISSUE TITLE
flink  on  yarn  集群跑任务问题

### ISSUE THREAD

**Issue by qy513449931** [ivi-ru/flink-clickhouse-sink#17]
请问在flink  集群任务中 ClickHouseSinkConst.FAILED_RECORDS_PATH  这个参数填写什么地址，是hdfs地址还是本地地址，如果是本地地址，一旦任务提交到集群，都不知道在那台服务器建立地址

**Comment by ashulenko** [comment]
@qy513449931 hello.
please, write in english.

**Comment by qy513449931** [comment]
Excuse me? ClickHouseSinkConst.FAILED_ RECORDS_ Does path address support HDFS address？

**Comment by ashulenko** [comment]
@qy513449931 No, does not. There is only storing failed records to local FS in version 1.3.1
