### ISSUE TITLE
the distribution of resource，urgent and serious problems

### ISSUE THREAD

**Issue by songlingling0012** [ivi-ru/flink-clickhouse-sink#18]
Urgent and serious problems！！！
In the production of enviroment, I used flink-clickhouse-sink-1.1.0 and my flink version is 1.9.3. My configurations is as follow:
ClickHouseSinkConst.TIMEOUT_SEC=60
ClickHouseSinkConst.FAILED_RECORDS_PATH=
ClickHouseSinkConst.NUM_WRITERS=64
ClickHouseSinkConst.NUM_RETRIES=3
ClickHouseSinkConst.QUEUE_MAX_CAPACITY=10000
when my program runs normally for a period of time and then reports an error:
ru.ivi.opensource.flinkclickhousesink.applied.ClickhouseWriter$WriterTask Error While inserting data 
java.lang.InterruptedException  at java.util.concurrent.locks.AbstractQueueSynchronizer.acquireInterruptibly(AbstractQueueSynchronizer.java:1220)....

I would like to know what caused this exception......
can I fix this if I upgrade to the latest version 1.31?
I'm very anxious. Thank you for your help!!

**Comment by ashulenko** [comment]
@songlingling0012, please let me know have you solved the problem by changing sink version to 1.3.1?

**Comment by songlingling0012** [comment]
> @songlingling0012, please let me know have you solved the problem by changing sink version to 1.3.1?

I don't remember exactly, but I think it was solved by the revised version.  Sorry, I'm not very sure right now, but you can try  it

**Comment by songlingling0012** [comment]
> @songlingling0012, please let me know have you solved the problem by changing sink version to 1.3.1?

Another possibility that I can think of is that changing the timeout might also work

**Comment by ashulenko** [comment]
Thanks for the your reply.
