### ISSUE TITLE
How to insert array type data into clickhouse

### ISSUE THREAD

**Issue by xiaomaiyun** [ivi-ru/flink-clickhouse-sink#19]
How to insert array type data into clickhouse。
CREATE TABLE tutorial.user3
(
    id UInt64 comment '消息ID',
    name String comment '名称',
	addr Array(UInt64) comment '地址'
)
ENGINE = MergeTree()
primary key (id)
ORDER BY (id);

**Comment by ashulenko** [comment]
@xiaomaiyun Hi!
Insert array type data to example table this way:
```
INSERT INTO tutorial.user3 VALUES (1,'foo',[1,2]);
``` 
Hope this helps.
