### ISSUE TITLE
 how to process deletion on clickhouse 

### ISSUE THREAD

**Issue by baisui1981** [ivi-ru/flink-clickhouse-sink#31]
as checked the document of [flink-clickhouse-sink](https://github.com/ivi-ru/flink-clickhouse-sink) ,I have a question how to execute deletion on Clickhouse , it seems that has not been  mentioned

**Comment by mchernyakov** [comment]
@baisui1981 hi, [flink-clickhouse-sink](https://github.com/ivi-ru/flink-clickhouse-sink) does not have such an option.
It works only with inserts, check here https://github.com/ivi-ru/flink-clickhouse-sink/blob/master/src/main/java/ru/ivi/opensource/flinkclickhousesink/applied/ClickHouseWriter.java#L198 .
