### ISSUE TITLE
wrong clickhouse ip config but kafka offset commited

### ISSUE THREAD

**Issue by SeaAndHillMe** [ivi-ru/flink-clickhouse-sink#37]
wrong clickhouse ip config but kafka offset commited

**Comment by SeaAndHillMe** [comment]
@aleksanchezz 172.23.4.6:8123,172.23.4.58:8123,172.23.4.59:8123  config like this  ,the job will not fail and not record the fail date

**Comment by mchernyakov** [comment]
@SeaAndHillMe we're going to merge and release https://github.com/ivi-ru/flink-clickhouse-sink/pull/34 next month, so it should solve the issue with configs, I suppose.

**Comment by mchernyakov** [comment]
released
