### ISSUE TITLE
How to insert an csv row into a clickhouse db.table?

### ISSUE THREAD

**Issue by JoshuaYin** [ivi-ru/flink-clickhouse-sink#6]
I read data from Kafka and transfer data into clickhouse with flink.
And the data is csv row String, the data format on clickhouse is DB.

**Comment by mchernyakov** [comment]
@JoshuaYin so, let me clarify, you are reading data from kafka and the format is CSV (String), and you want to send these rows to Clickhouse, correct?

Have you tried to implement your own converter, as we have in the example? https://github.com/ivi-ru/flink-clickhouse-sink#in-code

**Comment by JoshuaYin** [comment]
emmmmm，I've resolve the problem with the method like implement my  own converter.
Thx~
By the way,  the sink is so convenient~

**Comment by mchernyakov** [comment]
ok, closing this issue
